"""Add added_by_user_id to physical_book for tracking book ownership

Revision ID: 7ff452bcb5e8
Revises: c0d675d8d801
Create Date: 2025-11-11 22:58:32.363570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff452bcb5e8'
down_revision = 'c0d675d8d801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['added_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('added_by_user_id')

    # ### end Alembic commands ###
