"""Rename student table to user and make fields nullable

Revision ID: c0d2d5501ca6
Revises: d9861600ffc5
Create Date: 2025-11-06 19:14:36.685088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0d2d5501ca6'
down_revision = 'd9861600ffc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_constraint('loan_ibfk_2', type_='foreignkey')

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('subscription_ibfk_1', type_='foreignkey')

    # Rename table from student to user
    op.rename_table('student', 'user')
    
    # Update column nullability
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name', existing_type=sa.String(length=150), nullable=True)
        batch_op.alter_column('roll_no', existing_type=sa.String(length=64), nullable=True)
        batch_op.alter_column('joined_at', existing_type=sa.DateTime(), nullable=True)
        batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=True)
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        
        # Rename indexes
        batch_op.drop_index('ix_student_email')
        batch_op.drop_index('ix_student_roll_no')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_roll_no'), ['roll_no'], unique=True)

    # Recreate foreign key constraints
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_foreign_key('loan_ibfk_2', 'user', ['student_id'], ['id'])

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_foreign_key('subscription_ibfk_1', 'user', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraints first
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_constraint('subscription_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_constraint('loan_ibfk_2', type_='foreignkey')

    # Rename table back from user to student
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_roll_no'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('is_verified')
        batch_op.alter_column('is_active', existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column('joined_at', existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column('roll_no', existing_type=sa.String(length=64), nullable=False)
        batch_op.alter_column('name', existing_type=sa.String(length=150), nullable=False)
        batch_op.create_index('ix_student_roll_no', ['roll_no'], unique=True)
        batch_op.create_index('ix_student_email', ['email'], unique=True)

    op.rename_table('user', 'student')

    # Recreate foreign key constraints
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.create_foreign_key('loan_ibfk_2', 'student', ['student_id'], ['id'])

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_foreign_key('subscription_ibfk_1', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
