"""Add related_courses field to physical_book

Revision ID: c565fb87c0c8
Revises: 1c72ed319bda
Create Date: 2025-10-11 18:22:22.574633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c565fb87c0c8'
down_revision = '1c72ed319bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_courses', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('physical_book', schema=None) as batch_op:
        batch_op.drop_column('related_courses')

    # ### end Alembic commands ###
