"""add_payment_id_to_loan_table

Revision ID: c64c44b631e6
Revises: c0d2d5501ca6
Create Date: 2025-11-06 23:10:21.957348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64c44b631e6'
down_revision = 'c0d2d5501ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan', schema=None) as batch_op:
        batch_op.drop_column('payment_id')

    # ### end Alembic commands ###
