"""Initial database setup with new models

Revision ID: d9861600ffc5
Revises: 
Create Date: 2025-11-04 19:24:20.176218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9861600ffc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('otp_code', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_email'), ['email'], unique=False)

    op.create_table('publication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publication_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_publication_title'), ['title'], unique=False)

    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_student_roll_no'), ['roll_no'], unique=True)

    op.create_table('audiobook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('narrator', sa.String(length=150), nullable=True),
    sa.Column('librivox_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audiobook_librivox_id'), ['librivox_id'], unique=True)

    op.create_table('ebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ebook_external_id'), ['external_id'], unique=True)

    op.create_table('physical_book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('total_copies', sa.Integer(), nullable=False),
    sa.Column('available_copies', sa.Integer(), nullable=False),
    sa.Column('related_courses', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['publication.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'BASIC', 'PRO', 'MAX', name='subscriptiontierenum'), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audiobook_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_url', sa.String(length=500), nullable=False),
    sa.Column('chapter_title', sa.String(length=300), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobook.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_url')
    )
    op.create_table('ebook_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_format', sa.String(length=20), nullable=False),
    sa.Column('content_url', sa.String(length=500), nullable=False),
    sa.Column('ebook_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ebook_id'], ['ebook.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_url')
    )
    op.create_table('loan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borrowed_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('returned_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('BORROWED', 'RETURNED', 'OVERDUE', 'LOST', name='loanstatusenum'), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['physical_book.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'CANCELLED', name='finestatusenum'), nullable=False),
    sa.Column('issued_date', sa.DateTime(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['loan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fine')
    op.drop_table('loan')
    op.drop_table('ebook_format')
    op.drop_table('audiobook_chapter')
    op.drop_table('subscription')
    op.drop_table('physical_book')
    with op.batch_alter_table('ebook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ebook_external_id'))

    op.drop_table('ebook')
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiobook_librivox_id'))

    op.drop_table('audiobook')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_roll_no'))
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    with op.batch_alter_table('publication', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publication_title'))
        batch_op.drop_index(batch_op.f('ix_publication_author'))

    op.drop_table('publication')
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_email'))

    op.drop_table('otp')
    # ### end Alembic commands ###
